### ISSUE TITLE
How to apply in real life project?

### ISSUE THREAD

**Issue by viswongdev** [carpediem-av/rtsp2html5#1]
I have a ip camera that get an img streaming videos by accessing. the ip address. How to convert it to html 5 video element?

**Comment by carpediem-av** [comment]
1. Make new instance of Linux server (for example Debian) or use existing.
2. Install Apache, PHP 7.0+ and FFMpeg.
3. Get an SSL certificate for your server and install it (optional but highly recommended).
4. Сopy files of my script to root www directory of Apache.
5. Open "camera.php" in text editor and specify your security key (minimum 12 random chars; A-Z, a-z and 0-9 are allowed) in the "$key" variable. Specify in the "$redirectToIfBackground" variable where to redirect from the background tabs (i.e. url).
6. Place links to camera.php on the pages of your broadcasting site in the following format: 
    camera.php?a=<rtsp-link_in_base64>&b=<your_security_key>&c=<rtsp-link_to_the_second_stream_in_base64>. In this case, the "c" parameter is optional, but very desirable.

Converting an RTSP link to base64 can be done using the service https://www.utilities-online.info/base64 and In the resulting string, replace each "=" character with string "%3D". RTSP links can be found in the camera documentation. You can also do this through the third-party utility named "Onvif Device Manager".
