### ISSUE TITLE
The generated video link does not work properly？

### ISSUE THREAD

**Issue by chcmq** [carpediem-av/rtsp2html5#2]
![image](https://user-images.githubusercontent.com/30547484/223399550-597e4ecf-30c9-4590-b9b3-8ad4ba87ed15.png)

**Comment by carpediem-av** [comment]
I'm sure the link is generated correctly. In any case, I have been using the program for a long time. Try setting the camera to H.264 encoding instead of H.264+ or H.265. It is also possible that the RTSP link is wrong or the camera is not available (check with VLC for example).

**Comment by chcmq** [comment]
I have connected correctly, but there will be a delay of 10 seconds, how do I need to optimize it

**Comment by chcmq** [comment]
> I'm sure the link is generated correctly. In any case, I have been using the program for a long time. Try setting the camera to H.264 encoding instead of H.264+ or H.265. It is also possible that the RTSP link is wrong or the camera is not available (check with VLC for example).

I have connected correctly, but there will be a delay of 10 seconds, how do I need to optimize it

**Comment by carpediem-av** [comment]
It is completely impossible to remove the delay - this is a drawback of this technology. To minimize delay, reduce the keyframe interval (I-frame interval) on the camera by setting it to the same as frame rate per second. In other words, if FPS=25, then I-frame interval=25. And yet - the delay is even less when viewing in MJPEG format.
![image](https://user-images.githubusercontent.com/80209500/225991019-af2e5ba3-cd48-4e2c-a078-4a3d9425056e.png)
